In [3]:
import pandas as pd
# Load the dataset 
raw_data_url = "https://raw.githubusercontent.com/eeberman/machine_learning_intro/master/Ames-Housing-Analysis/Data/AmesHousing.csv"
df = pd.read_csv(r"C:\Users\elieberm1\Documents\Python Scripts\machine_learning_self\Ames-Housing-Analysis\Data\Raw\AmesHousing.csv")
print(df.head())

   Order        PID  MS SubClass MS Zoning  Lot Frontage  Lot Area Street  \
0      1  526301100           20        RL         141.0     31770   Pave
1      2  526350040           20        RH          80.0     11622   Pave
2      3  526351010           20        RL          81.0     14267   Pave
3      4  526353030           20        RL          93.0     11160   Pave
4      5  527105010           60        RL          74.0     13830   Pave

  Alley Lot Shape Land Contour  ... Pool Area Pool QC  Fence Misc Feature  \
0   NaN       IR1          Lvl  ...         0     NaN    NaN          NaN
1   NaN       Reg          Lvl  ...         0     NaN  MnPrv          NaN
2   NaN       IR1          Lvl  ...         0     NaN    NaN         Gar2
3   NaN       Reg          Lvl  ...         0     NaN    NaN          NaN
4   NaN       IR1          Lvl  ...         0     NaN  MnPrv          NaN

  Misc Val Mo Sold Yr Sold Sale Type  Sale Condition  SalePrice
0        0       5    2010       WD           Normal     215000
1        0       6    2010       WD           Normal     105000
2    12500       6    2010       WD           Normal     172000
3        0       4    2010       WD           Normal     244000
4        0       3    2010       WD           Normal     189900

[5 rows x 82 columns]

In [4]:
# Define the square footage features relevant to living space
square_footage_features = [
    'Gr Liv Area',  # Above ground living area
    'Total Bsmt SF',  # Total basement area
    '1st Flr SF',  # First floor area
    '2nd Flr SF',  # Second floor area, if applicable
    'BsmtFin SF 1',  # Finished basement area 1
    'BsmtFin SF 2',  # Finished basement area 2
    'Bsmt Unf SF',  # Unfinished basement area
    'Low Qual Fin SF'  # Low quality finished area
]

# Calculate the total square footage for living space
df['square_footage_total'] = df[square_footage_features].sum(axis=1)

# Print the selected feature names
print("Features included in square_footage_total:")
print(square_footage_features)

# Print the first few rows of the calculated total square footage
print(df[['square_footage_total']].head(10))
# Check and redescribe the dataset with square_footage_total included
df.describe()

Features included in square_footage_total:
['Gr Liv Area', 'Total Bsmt SF', '1st Flr SF', '2nd Flr SF', 'BsmtFin SF 1', 'BsmtFin SF 2', 'Bsmt Unf SF', 'Low Qual Fin SF']
   square_footage_total
0                5472.0
1                3556.0
2                5316.0
3                8440.0
4                5114.0
5                5060.0
6                5352.0
7                5120.0
8                6422.0
9                5596.0

,Order,PID,MS SubClass,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,...,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,SalePrice,square_footage_total
count,2930.00000,2.930000e+03,2930.000000,2440.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2907.000000,...,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000,2930.000000
mean,1465.50000,7.144645e+08,57.387372,69.224590,10147.921843,6.094881,5.563140,1971.356314,1984.266553,101.896801,...,47.533447,23.011604,2.592491,16.002048,2.243345,50.635154,6.216041,2007.790444,180796.060068,5101.892150
std,845.96247,1.887308e+08,42.638025,23.365335,7880.017759,1.411026,1.111537,30.245361,20.860286,179.112611,...,67.483400,64.139059,25.141331,56.087370,35.597181,566.344288,2.714492,1.316613,79886.692357,1610.506496
min,1.00000,5.263011e+08,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,12789.000000,668.000000
25%,733.25000,5.284770e+08,20.000000,58.000000,7440.250000,5.000000,5.000000,1954.000000,1965.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,2007.000000,129500.000000,4008.000000
50%,1465.50000,5.354536e+08,50.000000,68.000000,9436.500000,6.000000,5.000000,1973.000000,1993.000000,0.000000,...,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,160000.000000,4904.000000
75%,2197.75000,9.071811e+08,70.000000,80.000000,11555.250000,7.000000,6.000000,2001.000000,2004.000000,164.000000,...,70.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,213500.000000,5989.000000
max,2930.00000,1.007100e+09,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,...,742.000000,1012.000000,508.000000,576.000000,800.000000,17000.000000,12.000000,2010.000000,755000.000000,23504.000000